#!/bin/zsh
# Hand-managed prompt — not generated by shellgen.
# Matches the fish prompt: truncated pwd | git info | ❯ (single line)
# Transient: old prompts collapse to just the arrow.

[[ -o interactive ]] || return 0

autoload -Uz add-zsh-hook
setopt PROMPT_SUBST

# -- pwd truncation -----------------------------------------------------------

_prompt_parts_length() {
  local total=0 part
  for part in "$@"; do
    (( total += ${#part} ))
  done
  (( $# > 1 )) && (( total += $# - 1 ))
  printf '%s' "$total"
}

_prompt_truncate_tail() {
  local text="$1"
  local keep="$2"
  if (( keep <= 1 )); then
    printf '…'
    return
  fi
  local tail_len=$(( keep - 1 ))
  if (( tail_len >= ${#text} )); then
    printf '%s' "$text"
    return
  fi
  printf '…%s' "${text[-$tail_len,-1]}"
}

_prompt_max_width() {
  local cols=${COLUMNS:-80}
  local width=$(( cols - 30 ))
  (( width < 0 )) && width=0
  printf '%s' "$width"
}

_prompt_rendered_length() {
  local rendered
  rendered=$(print -P -- "$1")
  printf '%s' "${#rendered}"
}

_prompt_segment_limit() {
  local cols=$1
  if (( cols < 40 )); then
    printf '0'
  elif (( cols < 60 )); then
    printf '1'
  elif (( cols < 80 )); then
    printf '2'
  else
    printf '%s' "$cols"
  fi
}

_prompt_pwd() {
  local max_width=${1:-$(_prompt_max_width)}
  local cwd="${PWD/#$HOME/~}"
  local cols=${COLUMNS:-80}
  local budget=$(( max_width - 2 ))
  (( budget < 10 )) && budget=10

  local -a parts display_parts
  parts=("${(@s:/:)cwd}")
  display_parts=("${parts[@]}")
  local n=${#display_parts}
  local limit=$(_prompt_segment_limit "$cols")
  local length i part other keep start

  if (( limit == 0 && n > 2 )); then
    if [[ "${display_parts[1]}" == '' || "${display_parts[1]}" == '~' ]]; then
      display_parts=("${display_parts[1]}" '…' "${display_parts[$n]}")
    else
      display_parts=('…' "${display_parts[$n]}")
    fi
  elif (( limit < cols )); then
    for (( i=2; i<n; i++ )); do
      part="${display_parts[$i]}"
      if [[ -n "$part" && ${#part} -gt limit ]]; then
        display_parts[$i]="${part[1,limit]}"
      fi
    done
  fi

  n=${#display_parts}
  length=$(_prompt_parts_length "${display_parts[@]}")

  if (( length > budget && n > 2 )); then
    local -a compact_parts tail_parts candidate_parts
    start=1
    if [[ "${display_parts[1]}" == '' || "${display_parts[1]}" == '~' ]]; then
      compact_parts=("${display_parts[1]}")
      start=2
    else
      compact_parts=()
    fi

    tail_parts=("${display_parts[$n]}")
    for (( i=n-1; i>=start; i-- )); do
      candidate_parts=("${compact_parts[@]}" '…' "${display_parts[$i]}" "${tail_parts[@]}")
      if (( $(_prompt_parts_length "${candidate_parts[@]}") > budget )); then
        break
      fi
      tail_parts=("${display_parts[$i]}" "${tail_parts[@]}")
    done

    display_parts=("${compact_parts[@]}" '…' "${tail_parts[@]}")
    n=${#display_parts}
    length=$(_prompt_parts_length "${display_parts[@]}")
  fi

  if (( length > budget && n > 0 )); then
    other=0
    if (( n > 1 )); then
      other=$(_prompt_parts_length "${display_parts[@]:0:n-1}")
    fi
    keep=$(( budget - other - 1 ))
    (( keep < 1 )) && keep=1
    display_parts[$n]="$(_prompt_truncate_tail "${display_parts[$n]}" "$keep")"
  fi

  local out='' sep='' p seg
  for (( i=1; i<=n; i++ )); do
    p="${display_parts[$i]}"
    if (( i == 1 || i == n )); then
      seg="%F{14}${p}%f"
    elif [[ -z "$p" ]]; then
      seg=''
    else
      seg="%F{13}${p}%f"
    fi
    out+="${sep}${seg}"
    sep="%F{6}/%f"
  done
  printf '%s' "$out"
}

# -- git status ---------------------------------------------------------------

_prompt_git() {
  local max_width=${1:-24}
  local branch
  branch=$(git branch --show-current 2>/dev/null) || return

  if [[ -z "$branch" ]]; then
    branch=$(git tag --points-at HEAD 2>/dev/null | head -1)
    if [[ -n "$branch" ]]; then
      branch="#${branch}"
    else
      branch="@$(git rev-parse --short HEAD 2>/dev/null)"
    fi
  fi
  (( max_width < 4 )) && return

  local stat stash staged dirty untracked conflicted
  stat=$(git --no-optional-locks status --porcelain 2>/dev/null)
  stash=$(git stash list 2>/dev/null | wc -l | tr -d ' ')
  staged=$(print -r -- "$stat" | grep -c $'^[ADMR]' 2>/dev/null || true)
  dirty=$(print -r -- "$stat" | grep -c $'^.[ADMR]' 2>/dev/null || true)
  untracked=$(print -r -- "$stat" | grep -c $'^\?\?' 2>/dev/null || true)
  conflicted=$(print -r -- "$stat" | grep -c $'^UU' 2>/dev/null || true)
  staged=${staged:-0}; dirty=${dirty:-0}
  untracked=${untracked:-0}; conflicted=${conflicted:-0}

  local behind=0 ahead=0 upstream
  upstream=$(git rev-list --count --left-right \
    @{upstream}...HEAD 2>/dev/null) || true
  if [[ -n "$upstream" ]]; then
    behind=${upstream%$'\t'*}; ahead=${upstream#*$'\t'}
  fi

  # Calculate display length of status indicators so branch can be sized
  local suffix_len=0
  (( behind     > 0 )) && (( suffix_len += 2 + ${#behind} ))
  (( ahead      > 0 )) && (( suffix_len += 2 + ${#ahead} ))
  (( stash      > 0 )) && (( suffix_len += 2 + ${#stash} ))
  (( conflicted > 0 )) && (( suffix_len += 2 + ${#conflicted} ))
  (( staged     > 0 )) && (( suffix_len += 2 + ${#staged} ))
  (( dirty      > 0 )) && (( suffix_len += 2 + ${#dirty} ))
  (( untracked  > 0 )) && (( suffix_len += 2 + ${#untracked} ))

  local branch_budget=$(( max_width - suffix_len ))
  (( branch_budget < 2 )) && return
  (( ${#branch} > branch_budget )) && branch="$(_prompt_truncate_tail "$branch" "$branch_budget")"

  local color=10
  (( conflicted > 0 )) && color=9
  (( staged > 0 || dirty > 0 || untracked > 0 )) && color=11

  printf '%%F{%d}%s%%f' "$color" "$branch"
  (( behind     > 0 )) && printf ' %%F{10}⇣%d%%f' "$behind"
  (( ahead      > 0 )) && printf ' %%F{10}⇡%d%%f' "$ahead"
  (( stash      > 0 )) && printf ' %%F{10}*%d%%f'  "$stash"
  (( conflicted > 0 )) && printf ' %%F{9}~%d%%f'   "$conflicted"
  (( staged     > 0 )) && printf ' %%F{11}+%d%%f'  "$staged"
  (( dirty      > 0 )) && printf ' %%F{11}!%d%%f'  "$dirty"
  (( untracked  > 0 )) && printf ' %%F{12}?%d%%f'  "$untracked"
}

# -- arrow --------------------------------------------------------------------

_prompt_arrow() {
  local last=$1
  local color; (( last == 0 )) && color=10 || color=9
  local arrow='❯'; [[ "$KEYMAP" == vicmd ]] && arrow='❮'
  printf '%%F{%d}%s%%f ' "$color" "$arrow"
}

# -- prompt build -------------------------------------------------------------

_prompt_last_status=0
_prompt_cmd_start=$SECONDS

_prompt_build() {
  local last=$1 max_width pwd_str git_str arrow_str pwd_len arrow_len git_budget
  max_width=$(_prompt_max_width)
  arrow_str=$(_prompt_arrow "$last")
  arrow_len=$(_prompt_rendered_length "$arrow_str")

  local in_git=0
  git rev-parse --is-inside-work-tree &>/dev/null && in_git=1

  local pwd_budget=$(( max_width - arrow_len - 2 ))
  (( pwd_budget < 10 )) && pwd_budget=10
  pwd_str=$(_prompt_pwd "$pwd_budget")
  pwd_len=$(_prompt_rendered_length "$pwd_str")

  git_budget=$(( max_width - pwd_len - arrow_len - 2 ))
  if (( git_budget >= 4 && in_git )); then
    git_str=$(_prompt_git "$git_budget")
  else
    git_str=''
  fi

  local p="${pwd_str}"
  [[ -n "$git_str" ]] && p+=" ${git_str}"
  p+=" ${arrow_str}"
  PROMPT="$p"
}

# -- transient prompt ---------------------------------------------------------
# On Enter, collapse the full prompt to just the arrow, then execute.

_transient_accept_line() {
  PROMPT="$(_prompt_arrow "$_prompt_last_status")"
  zle reset-prompt
  zle .accept-line
}
zle -N accept-line _transient_accept_line

# Ctrl-C: collapse current prompt, then abort (precmd rebuilds full prompt)
_transient_int() {
  PROMPT="$(_prompt_arrow "$_prompt_last_status")"
  zle reset-prompt
  zle send-break
}
zle -N _transient_int
bindkey '^C' _transient_int

# -- hooks --------------------------------------------------------------------

_prompt_precmd() {
  _prompt_last_status=$?
  _prompt_build "$_prompt_last_status"
  RPROMPT=''
}

_prompt_preexec() {
  local elapsed=$(( SECONDS - _prompt_cmd_start ))
  if (( elapsed >= 3 )); then
    local t
    if (( elapsed < 60 )); then
      t="${elapsed}s"
    elif (( elapsed < 3600 )); then
      t="$((elapsed/60))m$((elapsed%60))s"
    else
      t="$((elapsed/3600))h$((elapsed%3600/60))m"
    fi
    RPROMPT="%F{8}${t}%f"
  fi
  _prompt_cmd_start=$SECONDS
}

add-zsh-hook precmd  _prompt_precmd
add-zsh-hook preexec _prompt_preexec

# Update arrow on vi mode change
zle-keymap-select() {
  _prompt_build "$_prompt_last_status"
  zle reset-prompt
}
zle -N zle-keymap-select
