#!/bin/zsh
# Hand-managed prompt — not generated by shellgen.
# Matches the fish prompt: truncated pwd | git info | ❯
# Transient: old prompts collapse to just the arrow.

[[ -o interactive ]] || return 0

autoload -Uz add-zsh-hook
setopt PROMPT_SUBST

# -- pwd truncation -----------------------------------------------------------

_prompt_pwd() {
  local cwd="${PWD/#$HOME/~}"
  local -a parts=("${(@s:/:)cwd}")
  local n=${#parts}
  local truncate=0
  (( ${#cwd} > COLUMNS / 2 )) && truncate=1

  local out='' sep='' p seg i
  for (( i=1; i<=n; i++ )); do
    p="${parts[$i]}"
    if (( i == 1 || i == n )); then
      seg="%F{14}${p}%f"
    elif [[ -z "$p" ]]; then
      seg=''
    elif (( truncate )); then
      seg="%F{13}${p[1]}%f"
    else
      seg="%F{14}${p}%f"
    fi
    out+="${sep}${seg}"
    sep="%F{6}/%f"
  done
  printf '%s' "$out"
}

# -- git status ---------------------------------------------------------------

_prompt_git() {
  local branch
  branch=$(git branch --show-current 2>/dev/null) || return

  if [[ -z "$branch" ]]; then
    branch=$(git tag --points-at HEAD 2>/dev/null | head -1)
    if [[ -n "$branch" ]]; then
      branch="#${branch}"
    else
      branch="@$(git rev-parse --short HEAD 2>/dev/null)"
    fi
  fi
  (( ${#branch} > 24 )) && branch="${branch[1,21]}..."

  local stat stash staged dirty untracked conflicted
  stat=$(git --no-optional-locks status --porcelain 2>/dev/null)
  stash=$(git stash list 2>/dev/null | wc -l | tr -d ' ')
  staged=$(print -r -- "$stat" | grep -c $'^[ADMR]' 2>/dev/null || true)
  dirty=$(print -r -- "$stat" | grep -c $'^.[ADMR]' 2>/dev/null || true)
  untracked=$(print -r -- "$stat" | grep -c $'^\?\?' 2>/dev/null || true)
  conflicted=$(print -r -- "$stat" | grep -c $'^UU' 2>/dev/null || true)
  staged=${staged:-0}; dirty=${dirty:-0}
  untracked=${untracked:-0}; conflicted=${conflicted:-0}

  local behind=0 ahead=0 upstream
  upstream=$(git rev-list --count --left-right \
    @{upstream}...HEAD 2>/dev/null) || true
  if [[ -n "$upstream" ]]; then
    behind=${upstream%$'\t'*}; ahead=${upstream#*$'\t'}
  fi

  local color=10
  (( conflicted > 0 )) && color=9
  (( staged > 0 || dirty > 0 || untracked > 0 )) && color=11

  printf '%%F{%d}%s%%f' "$color" "$branch"
  (( behind     > 0 )) && printf ' %%F{10}⇣%d%%f' "$behind"
  (( ahead      > 0 )) && printf ' %%F{10}⇡%d%%f' "$ahead"
  (( stash      > 0 )) && printf ' %%F{10}*%d%%f'  "$stash"
  (( conflicted > 0 )) && printf ' %%F{9}~%d%%f'   "$conflicted"
  (( staged     > 0 )) && printf ' %%F{11}+%d%%f'  "$staged"
  (( dirty      > 0 )) && printf ' %%F{11}!%d%%f'  "$dirty"
  (( untracked  > 0 )) && printf ' %%F{12}?%d%%f'  "$untracked"
}

# -- arrow --------------------------------------------------------------------

_prompt_arrow() {
  local last=$1
  local color; (( last == 0 )) && color=10 || color=9
  local arrow='❯'; [[ "$KEYMAP" == vicmd ]] && arrow='❮'
  printf '%%F{%d}%s%%f ' "$color" "$arrow"
}

# -- prompt build -------------------------------------------------------------

_prompt_last_status=0
_prompt_cmd_start=$SECONDS

_prompt_build() {
  local last=$1 pwd_str git_str arrow_str
  pwd_str=$(_prompt_pwd)
  git_str=$(_prompt_git)
  arrow_str=$(_prompt_arrow "$last")

  local p="${pwd_str}"
  [[ -n "$git_str" ]] && p+=" ${git_str}"
  p+=$'\n'"${arrow_str}"
  PROMPT="$p"
}

# -- transient prompt ---------------------------------------------------------
# On Enter, collapse the full prompt to just the arrow, then execute.

_transient_accept_line() {
  PROMPT="$(_prompt_arrow "$_prompt_last_status")"
  zle reset-prompt
  zle .accept-line
}
zle -N accept-line _transient_accept_line

# Ctrl-C: collapse current prompt, then abort (precmd rebuilds full prompt)
_transient_int() {
  PROMPT="$(_prompt_arrow "$_prompt_last_status")"
  zle reset-prompt
  zle send-break
}
zle -N _transient_int
bindkey '^C' _transient_int

# -- hooks --------------------------------------------------------------------

_prompt_precmd() {
  _prompt_last_status=$?
  _prompt_build "$_prompt_last_status"
  RPROMPT=''
}

_prompt_preexec() {
  local elapsed=$(( SECONDS - _prompt_cmd_start ))
  if (( elapsed >= 3 )); then
    local t
    if (( elapsed < 60 )); then
      t="${elapsed}s"
    elif (( elapsed < 3600 )); then
      t="$((elapsed/60))m$((elapsed%60))s"
    else
      t="$((elapsed/3600))h$((elapsed%3600/60))m"
    fi
    RPROMPT="%F{8}${t}%f"
  fi
  _prompt_cmd_start=$SECONDS
}

add-zsh-hook precmd  _prompt_precmd
add-zsh-hook preexec _prompt_preexec

# Update arrow on vi mode change
zle-keymap-select() {
  _prompt_build "$_prompt_last_status"
  zle reset-prompt
}
zle -N zle-keymap-select
