#!/bin/zsh
# Path: $ZDOTDIR/.zplugins
# Antidote plugins file

# Utils
ohmyzsh/ohmyzsh path:plugins/extract

# Editor
ohmyzsh/ohmyzsh path:plugins/magic-enter
ohmyzsh/ohmyzsh path:plugins/fancy-ctrl-z

# macOS
ohmyzsh/ohmyzsh path:plugins/iterm2 conditional:is-macos
zshzoo/macos conditional:is-macos

# Prompt
sindresorhus/pure kind:fpath
romkatv/powerlevel10k kind:fpath

# tmux
# ohmyzsh/ohmyzsh path:plugins/tmux

# fzf
mattmc3/zman
Aloxaf/fzf-tab

# zsh-users
zsh-users/zsh-completions kind:fpath path:src
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-autosuggestions
zsh-users/zsh-history-substring-search

# other
wfxr/forgit
# unixorn/git-extra-commands
