#!/bin/zsh
# Path: $ZDOTDIR/.zshrc
# Zsh rc file, loads after the .zshenv file in the $ZDOTDIR directory

### Init Powerlevel10k
# If you are using Powerlevel10k prompt, and want to use instant prompt, uncomment this.
# Enable Powerlevel10k instant prompt. Should stay close to the top of .zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Load Zsh lib files in alphabetical order
for _zshlib in $ZDOTDIR/lib/*.zsh; source $_zshlib; unset _zshlib

### Run the prologue
zshrc-finale
